# base
BG_COLOR = (36, 106, 115)
HEIGHT = 600
WIDTH = 600
SIZE = (HEIGHT, WIDTH)
GAME_TITLE = "Tic Tac Toe"
STROKE_WIDTH = 5
STROKE_COLOR = (255, 255, 255)
SIGN_COLOR = (246, 174, 45)
CROSS_MARGIN = 40

# enhanced
ASSETS_DIR = "assets"
BACKGROUND_IMAGE = "background.jpg"
BOARD_IMAGE = "board.png"
CIRCLE_IMAGE = "circle.png"
CROSS_IMAGE = "cross.png"
CROSSHAIR_IMAGE = "crosshair 2.png"
CELL_DELTA = 195
CELL_ORIGIN = 30
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)