__all__ = [
    "BG_COLOR",
    "HEIGHT",
    "WIDTH",
    "SIZE",
    "GAME_TITLE",
    "STROKE_WIDTH",
    "STROKE_COLOR",
    "SIGN_COLOR",
    "CROSS_MARGIN",
    "ASSETS_DIR",
    "BACKGROUND_IMAGE",
    "BOARD_IMAGE",
    "CIRCLE_IMAGE",
    "CROSS_IMAGE",
    "CROSSHAIR_IMAGE",
    "CELL_DELTA",
    "CELL_ORIGIN",
    "SCREEN_WIDTH",
    "SCREEN_HEIGHT",
    "SCREEN_SIZE",

]

# base
BG_COLOR = (36, 106, 115)
HEIGHT = 600
WIDTH = 600
SIZE = (HEIGHT, WIDTH)
GAME_TITLE = "Tic Tac Toe"
STROKE_WIDTH = 5
STROKE_COLOR = (255, 255, 255)
SIGN_COLOR = (246, 174, 45)
CROSS_MARGIN = 40

# enhanced
ASSETS_DIR = "assets"
BACKGROUND_IMAGE = "background.jpg"
BOARD_IMAGE = "board.png"
CIRCLE_IMAGE = "circle.png"
CROSS_IMAGE = "cross.png"
CROSSHAIR_IMAGE = "crosshair 2.png"
CELL_DELTA = 195
CELL_ORIGIN = 30
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)